name = "IPUToolkit"
uuid = "92e0b95a-4011-435a-96f4-10064551ddbe"
authors = ["Emily Dietrich <jakibaki@live.com>", "Luk Burchard <luk.burchard@gmail.com>"]
version = "0.1.0"

[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"

[compat]
Clang = "0.14, 0.17"
GPUCompiler = "0.19"
LLVM = "5"
Scratch = "1.1"
julia = "1.6"
libcxxwrap_julia_jll = "0.9.6"
